# Generated by Django 3.1.7 on 2021-08-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boilerplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
